function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 19-Feb-2025 19:19:57


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FRM_1/accY_sigstats/CrestFactor', 'FRM_1/accY_sigstats/Std', 'FRM_1/pwm1_sigstats/Std', 'FRM_1/pwm2_sigstats/CrestFactor', 'FRM_1/pwm2_sigstats/Std', 'FRM_1/pwm3_sigstats/CrestFactor', 'FRM_1/pwm3_sigstats/Std', 'FRM_1/pwm4_sigstats/CrestFactor', 'FRM_1/pwm4_sigstats/Std', 'FRM_1/pwm5_sigstats/CrestFactor', 'FRM_1/pwm5_sigstats/Std', 'FRM_1/esc6_sigstats/Mean', 'FRM_1/esc6_sigstats/RMS', 'FRM_1/vibeX_sigstats/Mean', 'FRM_1/vibeX_sigstats/PeakValue', 'FRM_1/vibeX_sigstats/RMS', 'FRM_1/vibeX_sigstats/Std', 'FRM_1/vibeY_sigstats/Mean', 'FRM_1/vibeY_sigstats/PeakValue', 'FRM_1/vibeY_sigstats/RMS', 'FRM_1/vibeY_sigstats/Std', 'FRM_1/vibeZ_sigstats/Mean', 'FRM_1/vibeZ_sigstats/PeakValue', 'FRM_1/vibeZ_sigstats/RMS', 'FRM_1/rate_sigstats_2/Std', 'FRM_1/rate_sigstats_5/PeakValue', 'FRM_1/rate_sigstats_5/RMS', 'FRM_1/rate_sigstats_5/Std', 'FRM_1/gyrZ_ps_spec/PeakFreq1', 'FRM_1/pwm1_ps_spec/PeakFreq1', 'FRM_1/pwm1_ps_spec/BandPower', 'FRM_1/pwm2_ps_spec/PeakFreq1', 'FRM_1/pwm2_ps_spec/BandPower', 'FRM_1/pwm3_ps_spec/BandPower', 'FRM_1/pwm4_ps_spec/PeakFreq1', 'FRM_1/pwm4_ps_spec/BandPower', 'FRM_1/pwm5_ps_spec/PeakFreq1', 'FRM_1/pwm5_ps_spec/BandPower', 'FRM_1/pwm6_ps_spec/PeakFreq1', 'FRM_1/esc1_ps_spec/PeakFreq1', 'FRM_1/esc5_ps_spec/PeakFreq1', 'FRM_1/curr3_ps_spec/PeakFreq1', 'FRM_1/curr6_ps_spec/PeakFreq1', 'FRM_1/desYaw_ps_spec/PeakFreq1', 'FRM_1/vibeX_ps_spec/BandPower', 'FRM_1/vibeY_ps_spec/BandPower', 'FRM_1/rate_ps_2_spec/PeakFreq1', 'FRM_1/rate_ps_4_spec/PeakFreq1', 'FRM_1/rate_ps_5_spec/BandPower', 'FRM_1/rate_ps_7_spec/PeakFreq1', 'FRM_1/rate_ps_10_spec/PeakFreq1'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '1'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateTree(...
    'MaxNumSplits', 20, ...
    'NumVariablesToSample', 'all');
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'AdaBoostM1', ...
    'NumLearningCycles', 30, ...
    'Learners', template, ...
    'LearnRate', 0.1, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'FRM_1/accY_sigstats/CrestFactor', 'FRM_1/accY_sigstats/Std', 'FRM_1/pwm1_sigstats/Std', 'FRM_1/pwm2_sigstats/CrestFactor', 'FRM_1/pwm2_sigstats/Std', 'FRM_1/pwm3_sigstats/CrestFactor', 'FRM_1/pwm3_sigstats/Std', 'FRM_1/pwm4_sigstats/CrestFactor', 'FRM_1/pwm4_sigstats/Std', 'FRM_1/pwm5_sigstats/CrestFactor', 'FRM_1/pwm5_sigstats/Std', 'FRM_1/esc6_sigstats/Mean', 'FRM_1/esc6_sigstats/RMS', 'FRM_1/vibeX_sigstats/Mean', 'FRM_1/vibeX_sigstats/PeakValue', 'FRM_1/vibeX_sigstats/RMS', 'FRM_1/vibeX_sigstats/Std', 'FRM_1/vibeY_sigstats/Mean', 'FRM_1/vibeY_sigstats/PeakValue', 'FRM_1/vibeY_sigstats/RMS', 'FRM_1/vibeY_sigstats/Std', 'FRM_1/vibeZ_sigstats/Mean', 'FRM_1/vibeZ_sigstats/PeakValue', 'FRM_1/vibeZ_sigstats/RMS', 'FRM_1/rate_sigstats_2/Std', 'FRM_1/rate_sigstats_5/PeakValue', 'FRM_1/rate_sigstats_5/RMS', 'FRM_1/rate_sigstats_5/Std', 'FRM_1/gyrZ_ps_spec/PeakFreq1', 'FRM_1/pwm1_ps_spec/PeakFreq1', 'FRM_1/pwm1_ps_spec/BandPower', 'FRM_1/pwm2_ps_spec/PeakFreq1', 'FRM_1/pwm2_ps_spec/BandPower', 'FRM_1/pwm3_ps_spec/BandPower', 'FRM_1/pwm4_ps_spec/PeakFreq1', 'FRM_1/pwm4_ps_spec/BandPower', 'FRM_1/pwm5_ps_spec/PeakFreq1', 'FRM_1/pwm5_ps_spec/BandPower', 'FRM_1/pwm6_ps_spec/PeakFreq1', 'FRM_1/esc1_ps_spec/PeakFreq1', 'FRM_1/esc5_ps_spec/PeakFreq1', 'FRM_1/curr3_ps_spec/PeakFreq1', 'FRM_1/curr6_ps_spec/PeakFreq1', 'FRM_1/desYaw_ps_spec/PeakFreq1', 'FRM_1/vibeX_ps_spec/BandPower', 'FRM_1/vibeY_ps_spec/BandPower', 'FRM_1/rate_ps_2_spec/PeakFreq1', 'FRM_1/rate_ps_4_spec/PeakFreq1', 'FRM_1/rate_ps_5_spec/BandPower', 'FRM_1/rate_ps_7_spec/PeakFreq1', 'FRM_1/rate_ps_10_spec/PeakFreq1'};
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2024b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FRM_1/accY_sigstats/CrestFactor', 'FRM_1/accY_sigstats/Std', 'FRM_1/pwm1_sigstats/Std', 'FRM_1/pwm2_sigstats/CrestFactor', 'FRM_1/pwm2_sigstats/Std', 'FRM_1/pwm3_sigstats/CrestFactor', 'FRM_1/pwm3_sigstats/Std', 'FRM_1/pwm4_sigstats/CrestFactor', 'FRM_1/pwm4_sigstats/Std', 'FRM_1/pwm5_sigstats/CrestFactor', 'FRM_1/pwm5_sigstats/Std', 'FRM_1/esc6_sigstats/Mean', 'FRM_1/esc6_sigstats/RMS', 'FRM_1/vibeX_sigstats/Mean', 'FRM_1/vibeX_sigstats/PeakValue', 'FRM_1/vibeX_sigstats/RMS', 'FRM_1/vibeX_sigstats/Std', 'FRM_1/vibeY_sigstats/Mean', 'FRM_1/vibeY_sigstats/PeakValue', 'FRM_1/vibeY_sigstats/RMS', 'FRM_1/vibeY_sigstats/Std', 'FRM_1/vibeZ_sigstats/Mean', 'FRM_1/vibeZ_sigstats/PeakValue', 'FRM_1/vibeZ_sigstats/RMS', 'FRM_1/rate_sigstats_2/Std', 'FRM_1/rate_sigstats_5/PeakValue', 'FRM_1/rate_sigstats_5/RMS', 'FRM_1/rate_sigstats_5/Std', 'FRM_1/gyrZ_ps_spec/PeakFreq1', 'FRM_1/pwm1_ps_spec/PeakFreq1', 'FRM_1/pwm1_ps_spec/BandPower', 'FRM_1/pwm2_ps_spec/PeakFreq1', 'FRM_1/pwm2_ps_spec/BandPower', 'FRM_1/pwm3_ps_spec/BandPower', 'FRM_1/pwm4_ps_spec/PeakFreq1', 'FRM_1/pwm4_ps_spec/BandPower', 'FRM_1/pwm5_ps_spec/PeakFreq1', 'FRM_1/pwm5_ps_spec/BandPower', 'FRM_1/pwm6_ps_spec/PeakFreq1', 'FRM_1/esc1_ps_spec/PeakFreq1', 'FRM_1/esc5_ps_spec/PeakFreq1', 'FRM_1/curr3_ps_spec/PeakFreq1', 'FRM_1/curr6_ps_spec/PeakFreq1', 'FRM_1/desYaw_ps_spec/PeakFreq1', 'FRM_1/vibeX_ps_spec/BandPower', 'FRM_1/vibeY_ps_spec/BandPower', 'FRM_1/rate_ps_2_spec/PeakFreq1', 'FRM_1/rate_ps_4_spec/PeakFreq1', 'FRM_1/rate_ps_5_spec/BandPower', 'FRM_1/rate_ps_7_spec/PeakFreq1', 'FRM_1/rate_ps_10_spec/PeakFreq1'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '1'});

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationEnsemble, 'KFold', 10);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
