function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 20-Feb-2025 09:39:52


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FRM_1/accX_sigstats/Mean', 'FRM_1/accX_sigstats/PeakValue', 'FRM_1/accX_sigstats/RMS', 'FRM_1/pwm1_sigstats/CrestFactor', 'FRM_1/pwm1_sigstats/Std', 'FRM_1/pwm2_sigstats/CrestFactor', 'FRM_1/pwm2_sigstats/PeakValue', 'FRM_1/pwm2_sigstats/Std', 'FRM_1/pwm5_sigstats/CrestFactor', 'FRM_1/pwm5_sigstats/PeakValue', 'FRM_1/pwm5_sigstats/Std', 'FRM_1/pwm6_sigstats/CrestFactor', 'FRM_1/pwm6_sigstats/PeakValue', 'FRM_1/pwm6_sigstats/Std', 'FRM_1/esc6_sigstats/Mean', 'FRM_1/desYaw_sigstats/Mean', 'FRM_1/desYaw_sigstats/PeakValue', 'FRM_1/desYaw_sigstats/RMS', 'FRM_1/yaw_sigstats/Mean', 'FRM_1/yaw_sigstats/PeakValue', 'FRM_1/yaw_sigstats/RMS', 'FRM_1/vibeX_sigstats/Mean', 'FRM_1/vibeX_sigstats/PeakValue', 'FRM_1/vibeX_sigstats/RMS', 'FRM_1/vibeX_sigstats/Std', 'FRM_1/vibeY_sigstats/Mean', 'FRM_1/vibeY_sigstats/PeakValue', 'FRM_1/vibeY_sigstats/RMS', 'FRM_1/vibeY_sigstats/Std', 'FRM_1/vibeZ_sigstats/Mean', 'FRM_1/vibeZ_sigstats/PeakValue', 'FRM_1/vibeZ_sigstats/RMS', 'FRM_1/rate_sigstats_2/CrestFactor', 'FRM_1/rate_sigstats_2/PeakValue', 'FRM_1/rate_sigstats_2/Std', 'FRM_1/rate_sigstats_5/PeakValue', 'FRM_1/rate_sigstats_5/RMS', 'FRM_1/rate_sigstats_5/Std', 'FRM_1/accX_sigstats_1/Mean', 'FRM_1/accX_sigstats_1/PeakValue', 'FRM_1/accX_sigstats_1/RMS', 'FRM_1/accX_sigstats_2/Mean', 'FRM_1/accX_sigstats_2/PeakValue', 'FRM_1/accX_sigstats_2/RMS', 'FRM_1/accX_ps_spec/BandPower', 'FRM_1/pwm2_ps_spec/BandPower', 'FRM_1/pwm5_ps_spec/BandPower', 'FRM_1/pwm6_ps_spec/BandPower', 'FRM_1/vibeX_ps_spec/BandPower', 'FRM_1/vibeY_ps_spec/BandPower', 'FRM_1/rate_ps_5_spec/BandPower'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '5'; '10'}, {'0' '5' '10'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateSVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true);
classificationSVM = fitcecoc(...
    predictors, ...
    response, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
svmPredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'FRM_1/accX_sigstats/Mean', 'FRM_1/accX_sigstats/PeakValue', 'FRM_1/accX_sigstats/RMS', 'FRM_1/pwm1_sigstats/CrestFactor', 'FRM_1/pwm1_sigstats/Std', 'FRM_1/pwm2_sigstats/CrestFactor', 'FRM_1/pwm2_sigstats/PeakValue', 'FRM_1/pwm2_sigstats/Std', 'FRM_1/pwm5_sigstats/CrestFactor', 'FRM_1/pwm5_sigstats/PeakValue', 'FRM_1/pwm5_sigstats/Std', 'FRM_1/pwm6_sigstats/CrestFactor', 'FRM_1/pwm6_sigstats/PeakValue', 'FRM_1/pwm6_sigstats/Std', 'FRM_1/esc6_sigstats/Mean', 'FRM_1/desYaw_sigstats/Mean', 'FRM_1/desYaw_sigstats/PeakValue', 'FRM_1/desYaw_sigstats/RMS', 'FRM_1/yaw_sigstats/Mean', 'FRM_1/yaw_sigstats/PeakValue', 'FRM_1/yaw_sigstats/RMS', 'FRM_1/vibeX_sigstats/Mean', 'FRM_1/vibeX_sigstats/PeakValue', 'FRM_1/vibeX_sigstats/RMS', 'FRM_1/vibeX_sigstats/Std', 'FRM_1/vibeY_sigstats/Mean', 'FRM_1/vibeY_sigstats/PeakValue', 'FRM_1/vibeY_sigstats/RMS', 'FRM_1/vibeY_sigstats/Std', 'FRM_1/vibeZ_sigstats/Mean', 'FRM_1/vibeZ_sigstats/PeakValue', 'FRM_1/vibeZ_sigstats/RMS', 'FRM_1/rate_sigstats_2/CrestFactor', 'FRM_1/rate_sigstats_2/PeakValue', 'FRM_1/rate_sigstats_2/Std', 'FRM_1/rate_sigstats_5/PeakValue', 'FRM_1/rate_sigstats_5/RMS', 'FRM_1/rate_sigstats_5/Std', 'FRM_1/accX_sigstats_1/Mean', 'FRM_1/accX_sigstats_1/PeakValue', 'FRM_1/accX_sigstats_1/RMS', 'FRM_1/accX_sigstats_2/Mean', 'FRM_1/accX_sigstats_2/PeakValue', 'FRM_1/accX_sigstats_2/RMS', 'FRM_1/accX_ps_spec/BandPower', 'FRM_1/pwm2_ps_spec/BandPower', 'FRM_1/pwm5_ps_spec/BandPower', 'FRM_1/pwm6_ps_spec/BandPower', 'FRM_1/vibeX_ps_spec/BandPower', 'FRM_1/vibeY_ps_spec/BandPower', 'FRM_1/rate_ps_5_spec/BandPower'};
trainedClassifier.ClassificationSVM = classificationSVM;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2024b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'FRM_1/accX_sigstats/Mean', 'FRM_1/accX_sigstats/PeakValue', 'FRM_1/accX_sigstats/RMS', 'FRM_1/pwm1_sigstats/CrestFactor', 'FRM_1/pwm1_sigstats/Std', 'FRM_1/pwm2_sigstats/CrestFactor', 'FRM_1/pwm2_sigstats/PeakValue', 'FRM_1/pwm2_sigstats/Std', 'FRM_1/pwm5_sigstats/CrestFactor', 'FRM_1/pwm5_sigstats/PeakValue', 'FRM_1/pwm5_sigstats/Std', 'FRM_1/pwm6_sigstats/CrestFactor', 'FRM_1/pwm6_sigstats/PeakValue', 'FRM_1/pwm6_sigstats/Std', 'FRM_1/esc6_sigstats/Mean', 'FRM_1/desYaw_sigstats/Mean', 'FRM_1/desYaw_sigstats/PeakValue', 'FRM_1/desYaw_sigstats/RMS', 'FRM_1/yaw_sigstats/Mean', 'FRM_1/yaw_sigstats/PeakValue', 'FRM_1/yaw_sigstats/RMS', 'FRM_1/vibeX_sigstats/Mean', 'FRM_1/vibeX_sigstats/PeakValue', 'FRM_1/vibeX_sigstats/RMS', 'FRM_1/vibeX_sigstats/Std', 'FRM_1/vibeY_sigstats/Mean', 'FRM_1/vibeY_sigstats/PeakValue', 'FRM_1/vibeY_sigstats/RMS', 'FRM_1/vibeY_sigstats/Std', 'FRM_1/vibeZ_sigstats/Mean', 'FRM_1/vibeZ_sigstats/PeakValue', 'FRM_1/vibeZ_sigstats/RMS', 'FRM_1/rate_sigstats_2/CrestFactor', 'FRM_1/rate_sigstats_2/PeakValue', 'FRM_1/rate_sigstats_2/Std', 'FRM_1/rate_sigstats_5/PeakValue', 'FRM_1/rate_sigstats_5/RMS', 'FRM_1/rate_sigstats_5/Std', 'FRM_1/accX_sigstats_1/Mean', 'FRM_1/accX_sigstats_1/PeakValue', 'FRM_1/accX_sigstats_1/RMS', 'FRM_1/accX_sigstats_2/Mean', 'FRM_1/accX_sigstats_2/PeakValue', 'FRM_1/accX_sigstats_2/RMS', 'FRM_1/accX_ps_spec/BandPower', 'FRM_1/pwm2_ps_spec/BandPower', 'FRM_1/pwm5_ps_spec/BandPower', 'FRM_1/pwm6_ps_spec/BandPower', 'FRM_1/vibeX_ps_spec/BandPower', 'FRM_1/vibeY_ps_spec/BandPower', 'FRM_1/rate_ps_5_spec/BandPower'};
predictors = inputTable(:, predictorNames);
response = inputTable.faultCode;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'0'; '5'; '10'}, {'0' '5' '10'});

% Set up holdout validation
cvp = cvpartition(response, 'Holdout', 0.38);
trainingPredictors = predictors(cvp.training, :);
trainingResponse = response(cvp.training, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateSVM(...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 2, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true);
classificationSVM = fitcecoc(...
    trainingPredictors, ...
    trainingResponse, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', classNames);

% Create the result struct with predict function
svmPredictFcn = @(x) predict(classificationSVM, x);
validationPredictFcn = @(x) svmPredictFcn(x);

% Add additional fields to the result struct


% Compute validation predictions
validationPredictors = predictors(cvp.test, :);
validationResponse = response(cvp.test, :);
[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);

% Compute validation accuracy
correctPredictions = (validationPredictions == validationResponse);
isMissing = ismissing(validationResponse);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
